environments:
  benrd: 
  bingrd:
  dev:
  prod-blue:
  prod-green: 
  prototype:

releases:
# virtualassistant
  - name: va-callback-{{ .Environment.Name }}
    chart: ../helm/charts/virtualassistant
    version: 0.0.1
    values:
      - overrides/virtualassistant.yaml.gotmpl
    labels:
        category: dts
        app: va-callback
        tier: server
    namespace: va-callback-{{ .Environment.Name }}
    installed: true
    wait: false
    force: false
