environments:
  benrd:
  bingrd:
  dev:
  main:
  prod-blue:
  prod-green:
  prototype:

releases:
# virtualassistant
  - name: va-callback-{{ requiredEnv "BRANCH" }}
    chart: ../helm/charts/virtualassistant
    version: 0.0.1
    values:
      - overrides/virtualassistant.yaml.gotmpl
    labels:
        category: dts
        app: va-callback
        tier: server
    namespace: va-callback-{{ requiredEnv "BRANCH"  }}
    installed: true
    wait: false
    force: false
