# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test and Lint

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Linting
        run: npm run lint

      - name: Unit Tests 🧪
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        run: npm run test
        # env:
        #   CI: true

      - name: Cypress end-to-end 🧪
        uses: cypress-io/github-action@v2
        env:
          CI: true
          NODE_ENV: production
        with:
          install: false
          start: npm run test:e2e